debug: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=taskmaster
    username: postgres
    password: revature
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*" # do not enable all Actuator endpoints when deploying to prod (customer-facing)

jwt:
  secret: 5468576D5A7133743677397A24432646294A404E635266556A586E3272357537